### ISSUE TITLE
Swift3 conversion ?

### ISSUE THREAD

**Issue by petaire92** [larrynatalicio/15DaysofAnimationsinSwift#4]
Hey man ! 

Thanks for your work. The lack of explanation forces me to decipher your code, which is probably better for learning.

However I was wondering if you're thinking about converting some or all of your work to swift 3?

**Comment by larrynatalicio** [comment]
Hey,

I do plan on converting the entire project to Swift 3. However I do not have a timeframe for when that will be complete. 

Thanks for reaching out and glad you checked out the project.

Best,
Larry
